config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  root 'static_pages#index'

  resources :admins, only: [:index]

  post '/admins/schedule', to: 'admins#change_status'
  get '/admins/schedule', to: 'admins#schedule'

  # scope :admins do 
  #   resources :schedule
  # end


  resources :user_pages, only: [:index, :show]

  resources :delivery_addresses, only: [:create]

  resources :orders, only: [:index, :create]

  resources :pickups, only: [:index, :create]

  resources :retrieves, only: [:index, :create]

  resources :boxes, only: [:update]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/box.rb
class Box < ActiveRecord::Base
  belongs_to :user
  has_many :histories
  has_one :warehouse_position
  has_many :order_contents
  has_many :orders, :through => :order_contents


  has_attached_file :avatar, 
    :storage => :s3, 
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }, 
    :styles => { :medium => "300x300>", :small => "150x150>", :thumb => "100x100>", :icon => "25x25>" }, 
    :default_url => "http://s3.amazonaws.com/boxful-admin/image/boximg2.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def default_image_url
    view_context.image_path('/static_pages/boximg2.png')
  end

  def s3_credentials
    {:bucket => ENV['S3_BUCKET'], 
      :access_key_id => ENV['ACCESS_KEY_ID'], 
      :secret_access_key =>ENV['SECRET_ACCESS_KEY']}
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :transits
  has_many :drivers, :through => :transits
end

app/models/delivery_address.rb
class DeliveryAddress < ActiveRecord::Base
  belongs_to :user
  has_many :orders
  has_many :histories
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :transits
  has_many :cars, :through => :transits
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :box
  belongs_to :location_type
  belongs_to :delivery_address
  belongs_to :transit
  belongs_to :warehouse_position
end

app/models/location_type.rb
class LocationType < ActiveRecord::Base
  has_many :histories
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_type
  belongs_to :delivery_address
  belongs_to :time_when
  has_many :order_contents
  has_many :boxes, :through => :order_contents
end

app/models/order_content.rb
class OrderContent < ActiveRecord::Base
  belongs_to :order
  belongs_to :box
end

app/models/order_type.rb
class OrderType < ActiveRecord::Base
  has_many :orders
end

app/models/time_when.rb
class TimeWhen < ActiveRecord::Base
  has_many :orders
end

app/models/transit.rb
class Transit < ActiveRecord::Base
  belongs_to :car
  belongs_to :driver
  has_many :histories
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :boxes
  has_many :delivery_addresses
#  has_many :billing_addresses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  has_many :warehouse_positions
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/retrieves_helper.rb
module RetrievesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/index.html.erb
<body>

  <!-- welcome-page S -->
  <div class="container-fluid welcome-page">

    <% if current_user %>
      <%= render :partial => 'navbar/private_nav' %>
    <% else %>
      <!-- home-nav S -->
      <nav class="navbar navbar-default navbar-fixed-top" id="home-nav" role="navigation">
        <div class="container" id="home-nav-container">
          <!-- toggle minimize S -->
          <div class="navbar-header" id="home-nav-toggle-minimize">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#home-nav-right-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
              <img id="logo-black" class="hide" src="<%= asset_path 'static_pages/boxful-logo-black.png' %>" alt="black-logo">
              <img id="logo-white" src="<%= asset_path 'static_pages/boxful-logo-white.png' %>" alt="white-logo">
            </a>
          </div>
          <!-- toggle minimize C -->

          <!-- home-nav-right-collapse S -->
          <div class="collapse navbar-collapse" id="home-nav-right-collapse">
            <ul class="nav navbar-nav navbar-right" id="home-nav-right-font">
              <li>
                <a id="nav-how-it-works" href="">How it works</a>
              </li>
              <li>
                <a id="nav-pricing" href="">Pricing</a>
              </li>
              <li>
                <a id="nav-faq" href="">FAQ</a>
              </li>
              <li>
                <a id="nav-login" href="#">Login</a>
              </li>
              <li>
                <button class="btn" id="nav-btn-gt">GET STARTED</button>
              </li>
            </ul>
          </div>
          <!-- home-nav-right-collapse C -->
        </div>
      </nav>
      <!-- home-nav C -->
    <% end %>

    <!-- home-box-1 S -->
    <div class="row" id="home-box-1">
      <div class="col-xs-12" id="box-1">
        <h1>YOUR INFINITE CLOSET</h1>
        <p>Simple storage from HK$49/month.
          <br>You click. We collect, store and deliver.</p>
      </div>
      <div id="home-box-1-content">
        <div class="col-xs-12 sign-up-form hide" id="sign-up-form-div">
          <h1 class="home-box-1-font">Sign Up</h1>
          <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:id => "sign_up_user"}, :format => :json, :remote => true ) do |f| %>
            <%= devise_error_messages! %>
            <div class="sign-up-input col-xs-offset-2 col-xs-8"><%= f.text_field :name, :placeholder => "Full Name", :class => "form-control" %></div>
            <div class="sign-up-input col-xs-offset-2 col-xs-8"><%= f.email_field :email, :placeholder => "Email", :class => "form-control" %></div>
            <div class="sign-up-input col-xs-offset-2 col-xs-8"><%= f.password_field :password, :placeholder => "Password, minimum 8 characters", :class => "form-control"%></div>
            <div class="sign-up-input col-xs-offset-2 col-xs-8"><%= f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => "form-control" %></div>
            <div class="sign-up-input col-xs-offset-2 col-xs-8"><%= f.submit "Sign up", :class => "btn btn-warning" %></div>
          <% end %>
        </div>

        <div class="col-xs-12 sign-in-form hide" id="sign-in-form-div">
          <h1 class="home-box-1-font">Sign In</h1>
          <%= form_for(resource, :as => resource_name, :url => session_path(resource_name) , :html => {:id => "sign_in_user"}, :format => :json, :remote => true) do |f| %>
            <%= devise_error_messages! %>
            <div class="sign-in-input col-xs-offset-2 col-xs-8"><%= f.email_field :email, :placeholder => "Email", :class => "form-control" %></div>
            <div class="sign-in-input col-xs-offset-2 col-xs-8"><%= f.password_field :password, :placeholder => "Password", :class => "form-control" %></div>
            <div class="sign-in-input col-xs-offset-2 col-xs-8"><%= f.submit "Sign In", :class => "btn btn-warning" %></div>
          <% end %>
        </div>
        <div>
          <button class="btn" id="pickup-btn">SCHEDULE FREE PICKUP</button>
        </div>
      </div>
    </div>
    <!-- home-box-1 C -->

    <!-- home-box-2 S -->
    <div class="row fonting" id="home-box-2">
      <div class="col-xs-12 section-title">
        <h1>HOW IT WORKS</h1>
        <img class="title-underline" src="<%= asset_path 'static_pages/title-underline.png' %>">
      </div>
      <div class="col-xs-12 col-sm-4 hiw-border">
        <img class="hiw-img" src="<%= asset_path 'static_pages/boximg1.png' %>">
        <h1>1</h1>
        <h2>Deliver.</h2>
        <p>We deliver durable,
          <br>water-resistant boxes
          <br>to your doorstep</p>
      </div>
      <div class="col-xs-12 col-sm-4 hiw-border">
        <img class="hiw-img" src="<%= asset_path 'static_pages/boximg2.png' %>">
        <h1>2</h1>
        <h2>Pack.</h2>
        <p>Pack your stuff
          <br>into our boxes and
          <br> we pick it up</p>
      </div>
      <div class="col-xs-12 col-sm-4 hiw-border">
        <img class="hiw-img" src="<%= asset_path 'static_pages/boximg3.png' %>">
        <h1>3</h1>
        <h2>Store.</h2>
        <p>We store your boxes
          <br>at our secure,
          <br>climate-controlled facility</p>
      </div>
    </div>
    <!-- home-box-2 C -->

    <!-- home-box-3 S -->
    <div class="row fonting" id="home-box-3">
      <div class="col-xs-12 section-title">
        <h1>MANAGE ONLINE</h1>
        <img class="title-underline" src="<%= asset_path 'static_pages/title-underline.png' %>">
      </div>
      <div class="col-xs-12 col-sm-7 mo-padding">
        <img class="mo-img" src="<%= asset_path 'static_pages/boximg4.png' %>">
      </div>
      <div class="col-xs-12 col-sm-5 mo-padding" id="mo-article">
        <h2>Convenience.</h2>
        <p>Create a visual catalogue on your computer or mobile device.
          <br> Manage your items online and retrieve your boxes with just a few clicks.</p>
      </div>
    </div>
    <!-- home-box-3 C -->

    <!-- home-box-4 S -->
    <div class="row fonting" id="home-box-4">
      <div class="col-xs-12 section-title">
        <h1>SECURITY</h1>
        <img class="title-underline" src="<%= asset_path 'static_pages/title-underline.png' %>">
      </div>
      <div class="col-xs-6 col-sm-3 s-padding">
        <img class="security-item" src="<%= asset_path 'static_pages/security-item1.png' %>">
        <h2>24/7<br>Surveillance</h2>
        <p>24-hour CCTV, manned
          <br>security and restricted
          <br>public access</p>
      </div>
      <div class="col-xs-6 col-sm-3 s-padding">
        <img class="security-item" src="<%= asset_path 'static_pages/security-item2.png' %>">
        <h2>Direct Pickups<br> and Deliveries</h2>
        <p>Professional moving team
          <br>picks-up and delivers
          <br>directly to and from our
          <br>facilities</p>
      </div>
      <div class="col-xs-6 col-sm-3 s-padding">
        <img class="security-item" src="<%= asset_path 'static_pages/security-item3.png' %>">
        <h2>Climate Controlled Facility</h2>
        <p>Temperature and humidity-
          <br>controlled with fire
          <br>protection systems</p>
      </div>
      <div class="col-xs-6 col-sm-3 s-padding">
        <img class="security-item" src="<%= asset_path 'static_pages/security-item4.png' %>">
        <h2>Free Insurance</h2>
        <p>Every box comes with free
          <br>insurance that insures up to
          <br>HK$1,000</p>
      </div>
    </div>
    <!-- home-box-4 C -->

    <!-- home-box-5 S -->
    <div class="row fonting" id="home-box-5">
      <div class="col-xs-12 section-title">
        <h1>PRICING</h1>
        <img class="title-underline" src="<%= asset_path 'static_pages/title-underline.png' %>">
      </div>
      <div class="col-xs-12 col-sm-6 p-padding">
        <img id="pricingbox" src="<%= asset_path 'static_pages/pricingbox.png' %>">
      </div>
      <div class="col-xs-12 col-sm-6 p-padding">
        <ul>
          <li>
            <h2>HK$49/month per box</h2>
          </li>
          <li>
            <p><strong>Free</strong> drop off of durable boxes</p>
          </li>
          <li>
            <p><strong>Free</strong> pick up of packed boxes</p>
          </li>
          <li>
            <p><strong>Free</strong> insurance with every box</p>
          </li>
          <li>
            <p><strong>No minimum</strong> order or contract period</p>
          </li>
          <li>
            <p>We return your boxes for HK$100 + HK$25 per box</p>
          </li>
          <li>
            <p class="weak-font">* Your billing cycle will begin once we’ve picked up your
              <br>boxes or two weeks after the drop-off date, whichever
              <br>date is earlier.We ask you to limit the weight of each box to 20kg.</p>
          </li>
        </ul>
      </div>
    </div>
    <!-- home-box-5 C -->
  </div>
  <!-- welcome-page C -->
</body>