config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  root 'static_pages#index'

  resources :admins, only: [:index]

  post '/admins/schedule', to: 'admins#change_status'
  get '/admins/schedule', to: 'admins#schedule'

  # scope :admins do 
  #   resources :schedule
  # end


  resources :user_pages, only: [:index, :show]

  resources :delivery_addresses, only: [:create]

  resources :orders, only: [:index, :create]

  resources :pickups, only: [:index, :create]

  resources :retrieves, only: [:index, :create]

  resources :boxes, only: [:update]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/box.rb
class Box < ActiveRecord::Base
  belongs_to :user
  has_many :histories
  has_one :warehouse_position
  has_many :order_contents
  has_many :orders, :through => :order_contents


  has_attached_file :avatar, 
    :storage => :s3, 
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }, 
    :styles => { :medium => "300x300>", :small => "150x150>", :thumb => "100x100>", :icon => "25x25>" }, 
    :default_url => "http://s3.amazonaws.com/boxful-admin/image/boximg2.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def default_image_url
    view_context.image_path('/static_pages/boximg2.png')
  end

  def s3_credentials
    {:bucket => ENV['S3_BUCKET'], 
      :access_key_id => ENV['ACCESS_KEY_ID'], 
      :secret_access_key =>ENV['SECRET_ACCESS_KEY']}
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :transits
  has_many :drivers, :through => :transits
end

app/models/delivery_address.rb
class DeliveryAddress < ActiveRecord::Base
  belongs_to :user
  has_many :orders
  has_many :histories
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :transits
  has_many :cars, :through => :transits
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :box
  belongs_to :location_type
  belongs_to :delivery_address
  belongs_to :transit
  belongs_to :warehouse_position
end

app/models/location_type.rb
class LocationType < ActiveRecord::Base
  has_many :histories
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_type
  belongs_to :delivery_address
  belongs_to :time_when
  has_many :order_contents
  has_many :boxes, :through => :order_contents
end

app/models/order_content.rb
class OrderContent < ActiveRecord::Base
  belongs_to :order
  belongs_to :box
end

app/models/order_type.rb
class OrderType < ActiveRecord::Base
  has_many :orders
end

app/models/time_when.rb
class TimeWhen < ActiveRecord::Base
  has_many :orders
end

app/models/transit.rb
class Transit < ActiveRecord::Base
  belongs_to :car
  belongs_to :driver
  has_many :histories
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :boxes
  has_many :delivery_addresses
#  has_many :billing_addresses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  has_many :warehouse_positions
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/retrieves_helper.rb
module RetrievesHelper
end

app/views/admins/index.html.erb
<div class="container-fluid private-page">

  <%= render :partial => 'navbar/admin_nav' %>

  <div class="col-xs-12 hide"> <!-- id="section-1"> -->
    <%= form_tag(admins_schedule_path, method: :get) do %>
      <%= date_field_tag(:date) %>
      <%= submit_tag(:schedule) %>
     <% end %>
  </div>

  <div class="col-xs-12" id="section-1">
    <% @orders.each do |order| %>
      <% address = order.delivery_address %>
      <div id='order-<%= order.id %>' class="order-divs col-xs-12">
        <div class="col-xs-6"id="order-address-details">
          <p><%= order.order_type.order_type %> @ <%= order.time_when.time %></p>
          <p>Address</p>
          <p><%= order.user.name %></p>
          <p><%= address.address1 %> ,<br><%= address.address2 %>,<br><%= address.region %>,<br><%= address.district %></p>
        </div>
        <div class="col-xs-6"id="order-content-details">
          <%= form_tag(admins_schedule_path, method: :post, format: :json, remote: true, :class => "order-status-form") do %>
            <% order.boxes.each do |box| %>
              <div>
                <%= label_tag box.id %>
                <%= select_tag(box.id, options_for_select([['Status', 0], ['dropped-off', 1], ['picked-up', 2], ['stored', 3]])) %>
              </div>
            <% end %>
            <div>
              <%= label_tag 'all' %>
              <%= select_tag(:all, options_for_select([['Status', 0], ['dropped-off', 1], ['picked-up', 2], ['stored', 3]])) %>
            </div>
            <div class="hide">
              <%= number_field_tag 'order_id', order.id %>
            </div>
            <div>
              <%= submit_tag(:update) %>
            </div>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boxful</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/navbar/_admin_nav.html.erb
<!-- a-nav S -->
<nav class="navbar navbar-default navbar-fixed-top" id="a-nav" role="navigation">
  <div class="container" id="a-nav-container">
    <!-- toggle minimize S -->
    <div class="navbar-header" id="a-nav-toggle-minimize">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#a-nav-right-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/admins">
        <img id="logo-black" src="<%= asset_path 'static_pages/boxful-logo-black.png' %>" alt="black-logo">
        <img id="logo-white" class="hide"src="<%= asset_path 'static_pages/boxful-logo-white.png' %>" alt="white-logo">
      </a>
    </div>
    <!-- toggle minimize C -->

    <!-- a-nav-right-collapse S -->
    <div class="collapse navbar-collapse" id="a-nav-right-collapse">
      <ul class="nav navbar-nav navbar-right" id="a-nav-right-font">
        <li>
          <%= link_to "Schedule", admins_path %>
        </li>
        <li>
          <%= link_to "Sign Out", destroy_admin_session_path, method: :delete %>
        </li>
      </ul>
    </div>
    <!-- a-nav-right-collapse C -->
  </div>
</nav>
<!-- a-nav C -->

app/views/navbar/_private_nav.html.erb
<!-- p-nav S -->
<nav class="navbar navbar-default navbar-fixed-top" id="p-nav" role="navigation">
  <div class="container" id="p-nav-container">
    <!-- toggle minimize S -->
    <div class="navbar-header" id="p-nav-toggle-minimize">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#p-nav-right-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img id="logo-black" src="<%= asset_path 'static_pages/boxful-logo-black.png' %>" alt="black-logo">
        <img id="logo-white" class="hide"src="<%= asset_path 'static_pages/boxful-logo-white.png' %>" alt="white-logo">
      </a>
    </div>
    <!-- toggle minimize C -->

    <!-- p-nav-right-collapse S -->
    <div class="collapse navbar-collapse" id="p-nav-right-collapse">
      <ul class="nav navbar-nav navbar-right" id="p-nav-right-font">
        <li>
          <%= link_to "My Boxes", user_pages_path, :id => "nav-my-stuff" %>
        </li>
        <li>
          <%= link_to "Retrieve", retrieves_path, :id => "nav-shedule-pickup" %>
        </li>
        <li>
          <%= link_to "Pickup", pickups_path, :id => "nav-shedule-pickup" %>
        </li>
        <li>
          <%= link_to "Get Boxes", orders_path, :method => :get, :id => "nav-shedule-pickup" %>
        </li>
        <li>
          <%= link_to "My Info", user_page_path(:id => current_user.id), :method => :get, :id => "nav-my-account" %>
        </li>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :id => "nav-sign-out" %>
        </li>
      </ul>
    </div>
    <!-- p-nav-right-collapse C -->
  </div>
</nav>
<!-- p-nav C -->