config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  root 'static_pages#index'

  resources :admins, only: [:index]

  post '/admins/schedule', to: 'admins#change_status'
  get '/admins/schedule', to: 'admins#schedule'

  # scope :admins do 
  #   resources :schedule
  # end


  resources :user_pages, only: [:index, :show]

  resources :delivery_addresses, only: [:create]

  resources :orders, only: [:index, :create]

  resources :pickups, only: [:index, :create]

  resources :retrieves, only: [:index, :create]

  resources :boxes, only: [:update]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/box.rb
class Box < ActiveRecord::Base
  belongs_to :user
  has_many :histories
  has_one :warehouse_position
  has_many :order_contents
  has_many :orders, :through => :order_contents


  has_attached_file :avatar, 
    :storage => :s3, 
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }, 
    :styles => { :medium => "300x300>", :small => "150x150>", :thumb => "100x100>", :icon => "25x25>" }, 
    :default_url => "http://s3.amazonaws.com/boxful-admin/image/boximg2.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def default_image_url
    view_context.image_path('/static_pages/boximg2.png')
  end

  def s3_credentials
    {:bucket => ENV['S3_BUCKET'], 
      :access_key_id => ENV['ACCESS_KEY_ID'], 
      :secret_access_key =>ENV['SECRET_ACCESS_KEY']}
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :transits
  has_many :drivers, :through => :transits
end

app/models/delivery_address.rb
class DeliveryAddress < ActiveRecord::Base
  belongs_to :user
  has_many :orders
  has_many :histories
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :transits
  has_many :cars, :through => :transits
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :box
  belongs_to :location_type
  belongs_to :delivery_address
  belongs_to :transit
  belongs_to :warehouse_position
end

app/models/location_type.rb
class LocationType < ActiveRecord::Base
  has_many :histories
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_type
  belongs_to :delivery_address
  belongs_to :time_when
  has_many :order_contents
  has_many :boxes, :through => :order_contents
end

app/models/order_content.rb
class OrderContent < ActiveRecord::Base
  belongs_to :order
  belongs_to :box
end

app/models/order_type.rb
class OrderType < ActiveRecord::Base
  has_many :orders
end

app/models/time_when.rb
class TimeWhen < ActiveRecord::Base
  has_many :orders
end

app/models/transit.rb
class Transit < ActiveRecord::Base
  belongs_to :car
  belongs_to :driver
  has_many :histories
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :boxes
  has_many :delivery_addresses
#  has_many :billing_addresses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  has_many :warehouse_positions
end

app/models/warehouse_position.rb
class WarehousePosition < ActiveRecord::Base
  belongs_to :warehouse
  belongs_to :box
  has_many :histories
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @order = Order.new
    @delivery_address = DeliveryAddress.new
    @delivery_addresses = current_user.delivery_addresses.order(:id)
    @time = TimeWhen.order(:id)
  end

  def create
    order = current_user.orders.new(order_params)
    if order.save
      for i in 1..params[:amount].to_i
      box = Box.create(:user_id => current_user.id)
      history = box.histories.create(:location_type_id => 2)
      order_content = OrderContent.create(box_id: box.id, order_id: order.id)
    end
      render json: {data: order, status: 201, success: true}
    else
      render json: {data: order, success: false, eMessage: order.errors.messages}
    end
  end

  private
  def order_params
    params.require(:order).permit(:order_type_id, :delivery_address_id, :date_when, :time_when_id)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/retrieves_helper.rb
module RetrievesHelper
end

app/helpers/user_pages_helper.rb
module UserPagesHelper
end

app/views/orders/index.html.erb
<div class="container-fluid private-page">

  <%= render :partial => 'navbar/private_nav' %>

  <div id="section-1">
    <div>
      <h1 id="order-page-messages"></h1>
    </div>
    <div class=<% if @delivery_addresses.empty? %>'col-xs-offset-2 col-xs-8'<% else %>'col-xs-offset-2 col-xs-8 hide'<% end %> id="initial-address-form-div">
      <h1>Please Enter Your Address</h1>
      <%= form_for @delivery_address, :url => delivery_addresses_path, :html => {:id => "initial_delivery_address", :class => "col-xs-12"}, :format => :json, :remote => true do |f| %>
        <div class="row">
          <%= f.label 'Address Name', :class => "col-xs-offset-3 col-xs-3" %>
          <%= f.text_field :name, :class => "col-xs-3" %>
        </div>
        <div class="row">
          <%= f.label :address1, :class => "col-xs-offset-3 col-xs-3" %>
          <%= f.text_field :address1, :class => "col-xs-3" %>
        </div>
        <div class="row">
          <%= f.label :address2, :class => "col-xs-offset-3 col-xs-3" %>
          <%= f.text_field :address2, :class => "col-xs-3" %>
        </div>
        <div class="row">
          <%= f.label :region, :class => "col-xs-offset-3 col-xs-3" %>
          <%= f.text_field :region, :class => "col-xs-3" %>
        </div>
        <div class="row">
          <%= f.label :district, :class => "col-xs-offset-3 col-xs-3" %>
          <%= f.text_field :district, :class => "col-xs-3" %>
        </div>
        <div class="row">
          <%= f.label :contact_number, :class => "col-xs-offset-3 col-xs-3" %>
          <%= f.number_field :contact_number, :class => "col-xs-3" %>
        </div>
        <div class="row hide">
          <%= f.label :default, :class => "col-xs-offset-3 col-xs-3" %>
          <%= f.check_box :default, checked: "checked"%>
        </div>
        <div class="row">
          <%= f.submit "Submit", :class => "col-xs-offset-4 col-xs-4 btn btn-info" %>
        </div>
      <% end %>
    </div>
    <div class=<% if @delivery_addresses.empty? %>'col-xs-offset-2 col-xs-8 hide'<% else %>'col-xs-offset-2 col-xs-8'<% end %> id="new-order-form-div">
      <h1>How many boxes do you need?</h1>
      <%= form_for @order, :url => orders_path, :html => {:id => "new-get-empty-order", :class => "col-xs-12"}, :format => :json, :remote => true  do |f| %>
        <div class="row">
          <label for="initial_box_amount" class="col-xs-offset-3 col-xs-3">Amount of Boxes</label>
          <input type="number" name="amount" id="initial_box_amount" max="30" min="1" class="col-xs-3">
        </div>
        <div class="row">
          <%= f.label :delivery_address_id, :class => "col-xs-offset-3 col-xs-3" %>
          <%= f.select :delivery_address_id, [], {}, :class => "col-xs-3" do %>
            <% if @delivery_addresses.empty? != true %>
              <% @delivery_addresses.each do |address| %>
                <% if address.default = 1 %>
                  <%= content_tag(:option, address.name, value: address.id, selected: "selected") %>
                <% else %>
                  <%= content_tag(:option, address.name, value: address.id) %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="row">
          <%= f.label "At Date", :class => "col-xs-offset-3 col-xs-3" %>
          <%= f.date_field :date_when, min: Date.today, :class => "col-xs-3" %>
        </div>
        <div class="row">
          <%= f.label "At Time", :class => "col-xs-offset-3 col-xs-3" %>
          <%= f.select :time_when_id, [], {}, {:class => "col-xs-3"} do %>
            <%= content_tag(:option, "Select Time", value: 0) %>)
            <% @time.each do |time| %>
              <%= content_tag(:option, time.time, value: time.id) %>
            <% end %>
          <% end %>
        </div>
        <div class="row hide">
          <%= f.number_field :order_type_id, value: 1 %>
        </div>
        <div class="row">
          <%= f.submit "Order", :class => "col-xs-offset-4 col-xs-4 btn btn-info"%>
        </div>
      <% end %>
    </div>
  </div>
</div>